# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_auto_20170901_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='url',
            new_name='waarneming_url',
        ),
    ]
