# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0003_auto_20170901_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='waarneming_url',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
