# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0004_auto_20170901_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000),
        ),
    ]
