# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0007_bioclassobservationstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='family',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='wikipedia_url_nl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='wikipedia_url_nl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='wikipedia_url_nl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
