# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0010_auto_20170930_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='wikipedia_url_nl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='wikipedia_url_nl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='waarneming_url',
            field=models.URLField(blank=True, db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='observer',
            name='waarneming_url',
            field=models.URLField(blank=True, db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikipedia_url_nl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
