# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0011_auto_20170930_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['group__slug', 'name_nl']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-datetime', 'group__slug']},
        ),
        migrations.AlterModelOptions(
            name='observer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['family__slug', 'name_nl']},
        ),
        migrations.AddField(
            model_name='observation',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
