# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0012_auto_20171001_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observer',
            old_name='waarneming_url',
            new_name='waarneming_user_url',
        ),
    ]
