# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0013_auto_20171001_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observer',
            name='waarneming_user_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=1000),
        ),
    ]
