# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0014_auto_20171001_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['family__slug']},
        ),
        migrations.AddField(
            model_name='family',
            name='n_observations',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='n_observations',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='n_observations',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='name_nl',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_nl',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_nl',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
    ]
