# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0015_auto_20171001_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observer',
            name='waarneming_user_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=1000, unique=True),
        ),
    ]
